@startuml
skinparam conditionEndStyle hline
start

if (self._current().token_type == token_type?) then (да)
  :self._index += 1;
  :return True;
  stop
else (нет)
  :return False;
  stop
endif
@enduml
