@startuml
start

:expression = self._parse_unary();

while (self._match(TokenType.AND)?) is (да)
  :operator = self._previous();
  :right = self._parse_unary();
  :expression = BinaryExpression(operator.value, expression, right);
endwhile (нет)

:return expression;
stop
@enduml
