@startuml
skinparam conditionEndStyle hline
start

if (token.token_type in {IDENTIFIER,\nLPAREN, NOT}?) then (да)
  :return ParserError("После завершенного выражения...");
  stop
else (нет)
  if (token.token_type == TokenType.RPAREN?) then (да)
    :return ParserError("Лишняя закрывающая скобка...");
    stop
  else (нет)
    :return ParserError("Некорректный хвост выражения...");
    stop
  endif
endif
@enduml
