@startuml
skinparam conditionEndStyle hline
start

if (isinstance(node, BinaryExpression)\nand node.operator == "\\/"?) then (да)
  :return _collect_disjunction_terms(node.left)\n+ _collect_disjunction_terms(node.right);
  stop
else (нет)
  :return [node];
  stop
endif
@enduml
